[build]
  base = "deeply-dwarf"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[forms]
  contact = { name = "Contact Form" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200